package peakSoft.enums;

public enum Specialization {
    FRONTEND_DEVELOPMENT,
    BACKEND_DEVELOPMENT,
    FULL_STACK_DEVELOPMENT,
    MOBILE_DEVELOPMENT,
    DATA_SCIENCE,
    CLOUD_COMPUTING,
    DEVOPS,
    SECURITY,
    SOFTWARE_ARCHITECTURE,
    TESTING_AND_QUALITY_ASSURANCE;
}
